from __future__ import annotations

import json
from pathlib import Path

from mineforgeai.minecraft.java_runtime import fabric_version_data, installed_java_summary, select_java_compatibility


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def generate_paper_plugin(workspace: Path, project_name: str, package_name: str, request: dict | None = None) -> list[Path]:
    root = workspace / project_name
    java_dir = root / "src" / "main" / "java" / Path(package_name.replace(".", "/"))
    items_dir = java_dir / "items"
    listeners_dir = java_dir / "listeners"
    commands_dir = java_dir / "commands"
    resources = root / "src" / "main" / "resources"
    compatibility = select_java_compatibility("paper", (request or {}).get("version"))
    effective_version = compatibility.effective_version
    api_version = ".".join(effective_version.split(".")[:2])
    files = []
    files.append(_write(root / ".gitignore", ".gradle/\nbuild/\n.idea/\nout/\n"))
    files.append(_write(root / "settings.gradle.kts", f'rootProject.name = "{project_name}"\n'))
    files.append(_write(root / "gradle.properties", f"org.gradle.jvmargs=-Xmx2G\norg.gradle.java.installations.auto-detect=true\npaperVersion={effective_version}\nprojectJavaVersion={compatibility.required_major}\n"))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated by MineForgeAI Omniverse for Paper {effective_version}.\n\nCommand: `/givesword`\nPermission: `{project_name.lower()}.givesword`\n\nRequested version: {compatibility.requested_version}\nSelected version: {effective_version}\nJava requirement: {compatibility.required_major}+\nDetected Java: {installed_java_summary()}\nCompatibility: {compatibility.message}\n"))
    files.append(_write(root / "build.gradle.kts", f"""plugins {{ java }}

repositories {{
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}}

dependencies {{
    compileOnly("io.papermc.paper:paper-api:${{property(\"paperVersion\")}}-R0.1-SNAPSHOT")
}}

java {{
    toolchain.languageVersion.set(JavaLanguageVersion.of(property("projectJavaVersion").toString().toInt()))
}}

tasks.withType<JavaCompile>().configureEach {{
    options.release.set(property("projectJavaVersion").toString().toInt())
}}
"""))
    files.append(_write(
        java_dir / f"{project_name}Plugin.java",
        f"package {package_name};\n\nimport {package_name}.commands.SwordCommand;\nimport {package_name}.items.SwordFactory;\nimport {package_name}.listeners.SwordListener;\nimport org.bukkit.Bukkit;\nimport org.bukkit.NamespacedKey;\nimport org.bukkit.command.PluginCommand;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class {project_name}Plugin extends JavaPlugin {{\n    private SwordFactory swordFactory;\n    private NamespacedKey swordKey;\n\n    @Override\n    public void onEnable() {{\n        saveDefaultConfig();\n        swordKey = new NamespacedKey(this, \"custom_sword\");\n        swordFactory = new SwordFactory(this, swordKey);\n        Bukkit.getPluginManager().registerEvents(new SwordListener(this, swordFactory), this);\n        PluginCommand command = getCommand(\"givesword\");\n        if (command != null) {{\n            command.setExecutor(new SwordCommand(swordFactory));\n        }}\n    }}\n}}\n"
    ))
    files.append(_write(
        items_dir / "SwordFactory.java",
        f"package {package_name}.items;\n\nimport org.bukkit.ChatColor;\nimport org.bukkit.Material;\nimport org.bukkit.NamespacedKey;\nimport org.bukkit.enchantments.Enchantment;\nimport org.bukkit.inventory.ItemFlag;\nimport org.bukkit.inventory.ItemStack;\nimport org.bukkit.inventory.ShapedRecipe;\nimport org.bukkit.inventory.meta.ItemMeta;\nimport org.bukkit.persistence.PersistentDataType;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class SwordFactory {{\n    private final JavaPlugin plugin;\n    private final NamespacedKey swordKey;\n\n    public SwordFactory(JavaPlugin plugin, NamespacedKey swordKey) {{\n        this.plugin = plugin;\n        this.swordKey = swordKey;\n        registerRecipe();\n    }}\n\n    public ItemStack createSword() {{\n        ItemStack sword = new ItemStack(Material.DIAMOND_SWORD);\n        ItemMeta meta = sword.getItemMeta();\n        if (meta != null) {{\n            meta.setDisplayName(ChatColor.AQUA + \"Omniverse Blade\");\n            meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_ENCHANTS);\n            meta.getPersistentDataContainer().set(swordKey, PersistentDataType.BYTE, Byte.valueOf((byte) 1));\n            sword.setItemMeta(meta);\n        }}\n        sword.addUnsafeEnchantment(Enchantment.SHARPNESS, 5);\n        return sword;\n    }}\n\n    public boolean isCustomSword(ItemStack stack) {{\n        if (stack == null || !stack.hasItemMeta()) {{\n            return false;\n        }}\n        ItemMeta meta = stack.getItemMeta();\n        return meta != null && meta.getPersistentDataContainer().has(swordKey, PersistentDataType.BYTE);\n    }}\n\n    private void registerRecipe() {{\n        ShapedRecipe recipe = new ShapedRecipe(new NamespacedKey(plugin, \"omniverse_blade\"), createSword());\n        recipe.shape(\" ND\", \" SN\", \"S  \" );\n        recipe.setIngredient('N', Material.NETHER_STAR);\n        recipe.setIngredient('D', Material.DIAMOND);\n        recipe.setIngredient('S', Material.STICK);\n        plugin.getServer().addRecipe(recipe);\n    }}\n}}\n"
    ))
    files.append(_write(
        listeners_dir / "SwordListener.java",
        f"package {package_name}.listeners;\n\nimport {package_name}.items.SwordFactory;\nimport org.bukkit.Particle;\nimport org.bukkit.Sound;\nimport org.bukkit.entity.Entity;\nimport org.bukkit.entity.LivingEntity;\nimport org.bukkit.entity.Player;\nimport org.bukkit.event.EventHandler;\nimport org.bukkit.event.Listener;\nimport org.bukkit.event.entity.EntityDamageByEntityEvent;\nimport org.bukkit.event.player.PlayerInteractEvent;\nimport org.bukkit.inventory.ItemStack;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class SwordListener implements Listener {{\n    private final JavaPlugin plugin;\n    private final SwordFactory swordFactory;\n\n    public SwordListener(JavaPlugin plugin, SwordFactory swordFactory) {{\n        this.plugin = plugin;\n        this.swordFactory = swordFactory;\n    }}\n\n    @EventHandler\n    public void onHit(EntityDamageByEntityEvent event) {{\n        Entity damager = event.getDamager();\n        Entity target = event.getEntity();\n        if (!(damager instanceof Player) || !(target instanceof LivingEntity)) {{\n            return;\n        }}\n        Player player = (Player) damager;\n        LivingEntity entity = (LivingEntity) target;\n        ItemStack item = player.getInventory().getItemInMainHand();\n        if (!swordFactory.isCustomSword(item)) {{\n            return;\n        }}\n        entity.getWorld().spawnParticle(Particle.END_ROD, entity.getLocation().add(0, 1, 0), 20, 0.3, 0.4, 0.3, 0.03);\n        entity.getWorld().playSound(entity.getLocation(), Sound.ENTITY_PLAYER_ATTACK_SWEEP, 1.0f, 1.2f);\n        player.setCooldown(item.getType(), plugin.getConfig().getInt(\"cooldown-seconds\", 5) * 20);\n    }}\n\n    @EventHandler\n    public void onRightClick(PlayerInteractEvent event) {{\n        ItemStack item = event.getItem();\n        if (!swordFactory.isCustomSword(item)) {{\n            return;\n        }}\n        Player player = event.getPlayer();\n        player.getWorld().spawnParticle(Particle.SOUL_FIRE_FLAME, player.getLocation().add(0, 1, 0), 30, 0.5, 0.5, 0.5, 0.02);\n        player.getWorld().playSound(player.getLocation(), Sound.ENTITY_LIGHTNING_BOLT_THUNDER, 0.5f, 1.7f);\n    }}\n}}\n"
    ))
    files.append(_write(
        commands_dir / "SwordCommand.java",
        f"package {package_name}.commands;\n\nimport {package_name}.items.SwordFactory;\nimport org.bukkit.command.Command;\nimport org.bukkit.command.CommandExecutor;\nimport org.bukkit.command.CommandSender;\nimport org.bukkit.entity.Player;\n\npublic final class SwordCommand implements CommandExecutor {{\n    private final SwordFactory swordFactory;\n\n    public SwordCommand(SwordFactory swordFactory) {{\n        this.swordFactory = swordFactory;\n    }}\n\n    @Override\n    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {{\n        if (!(sender instanceof Player)) {{\n            sender.sendMessage(\"Only players can use this command.\");\n            return true;\n        }}\n        Player player = (Player) sender;\n        player.getInventory().addItem(swordFactory.createSword());\n        player.sendMessage(\"You received the Omniverse Blade.\");\n        return true;\n    }}\n}}\n"
    ))
    files.append(_write(
        resources / "plugin.yml",
        f"name: {project_name}\nmain: {package_name}.{project_name}Plugin\nversion: 1.0.0\napi-version: '{api_version}'\ncommands:\n  givesword:\n    description: Gives the Omniverse Blade\n    usage: /givesword\n    permission: {project_name.lower()}.givesword\npermissions:\n  {project_name.lower()}.givesword:\n    default: op\n"
    ))
    files.append(_write(resources / "config.yml", "cooldown-seconds: 5\ntrail-enabled: true\nright-click-ability: true\n"))
    return files


def generate_fabric_mod(workspace: Path, project_name: str, package_name: str, request: dict | None = None) -> list[Path]:
    root = workspace / project_name
    java_dir = root / "src" / "main" / "java" / Path(package_name.replace(".", "/"))
    resources = root / "src" / "main" / "resources"
    compatibility = select_java_compatibility("fabric", (request or {}).get("version"))
    effective_version = compatibility.effective_version
    version_data = fabric_version_data(effective_version)
    files = []
    files.append(_write(root / ".gitignore", ".gradle/\nbuild/\n.idea/\nout/\nrun/\n"))
    files.append(_write(root / "settings.gradle.kts", f'rootProject.name = "{project_name}"\n'))
    files.append(_write(root / "gradle.properties", f"org.gradle.jvmargs=-Xmx2G\norg.gradle.java.installations.auto-detect=true\nminecraft_version={effective_version}\nyarn_mappings={version_data['yarn_mappings']}\nloader_version={version_data['loader_version']}\nfabric_version={version_data['fabric_version']}\nprojectJavaVersion={compatibility.required_major}\n"))
    files.append(_write(root / "build.gradle.kts", f"""plugins {{
    id(\"fabric-loom\") version \"1.7-SNAPSHOT\"
    java
}}

repositories {{
    mavenCentral()
    maven(\"https://maven.fabricmc.net/\")
}}

dependencies {{
    minecraft(\"com.mojang:minecraft:${{property(\\\"minecraft_version\\\")}}\")
    mappings(\"net.fabricmc:yarn:${{property(\\\"yarn_mappings\\\")}}:v2\")
    modImplementation(\"net.fabricmc:fabric-loader:${{property(\\\"loader_version\\\")}}\")
    modImplementation(\"net.fabricmc.fabric-api:fabric-api:${{property(\\\"fabric_version\\\")}}\")
}}

java {{
    toolchain.languageVersion.set(JavaLanguageVersion.of(property("projectJavaVersion").toString().toInt()))
}}

tasks.withType<JavaCompile>().configureEach {{
    options.release.set(property("projectJavaVersion").toString().toInt())
}}
"""))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated by MineForgeAI Omniverse for Fabric {effective_version}.\n\nRequested version: {compatibility.requested_version}\nSelected version: {effective_version}\nJava requirement: {compatibility.required_major}+\nDetected Java: {installed_java_summary()}\nCompatibility: {compatibility.message}\n"))
    files.append(_write(
        java_dir / f"{project_name}Mod.java",
        f"package {package_name};\n\nimport net.fabricmc.api.ModInitializer;\n\npublic final class {project_name}Mod implements ModInitializer {{\n    public static final String MOD_ID = \"{project_name.lower()}\";\n\n    @Override\n    public void onInitialize() {{\n    }}\n}}\n"
    ))
    files.append(_write(
        resources / "fabric.mod.json",
        json.dumps(
            {
                "schemaVersion": 1,
                "id": project_name.lower(),
                "version": "1.0.0",
                "name": project_name,
                "description": f"Generated Fabric mod for Minecraft {effective_version}",
                "environment": "*",
                "entrypoints": {"main": [f"{package_name}.{project_name}Mod"]},
                "depends": {"fabricloader": f">={version_data['loader_version']}", "minecraft": effective_version},
            },
            indent=2,
        ) + "\n"
    ))
    return files
