from __future__ import annotations

import json
import struct
import zlib
from pathlib import Path

from mineforgeai.minecraft.java_runtime import fabric_version_data, installed_java_summary, select_java_compatibility


PACK_FORMATS = [
    ((1, 21, 4), 61),
    ((1, 21, 2), 57),
    ((1, 21, 0), 48),
    ((1, 20, 5), 41),
    ((1, 20, 3), 26),
    ((1, 20, 2), 18),
    ((1, 20, 0), 15),
    ((1, 19, 4), 12),
    ((1, 19, 0), 10),
    ((1, 18, 0), 9),
    ((1, 17, 0), 8),
    ((1, 16, 2), 6),
    ((1, 15, 0), 5),
    ((1, 13, 0), 4),
]


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def _write_bytes(path: Path, content: bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return path


def _png_rgba(width: int, height: int, color: tuple[int, int, int, int]) -> bytes:
    def chunk(kind: bytes, data: bytes) -> bytes:
        payload = kind + data
        return struct.pack(">I", len(data)) + payload + struct.pack(">I", zlib.crc32(payload) & 0xFFFFFFFF)

    r, g, b, a = color
    raw = b"".join(b"\x00" + bytes([r, g, b, a]) * width for _ in range(height))
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")


def _pack_format(version: str | None) -> int:
    current = _version_tuple(version)
    for minimum, pack_format in PACK_FORMATS:
        if current >= minimum:
            return pack_format
    return 4


def _version_tuple(version: str | None) -> tuple[int, int, int]:
    parts = []
    for item in (version or "1.21.1").split("."):
        try:
            parts.append(int(item))
        except ValueError:
            break
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts[:3])


def _datapack_folder_names(version: str | None) -> dict[str, str]:
    if _version_tuple(version) >= (1, 21, 0):
        return {"function": "function", "advancement": "advancement", "recipe": "recipe"}
    return {"function": "functions", "advancement": "advancements", "recipe": "recipes"}


def _recipe_result(version: str | None, item_id: str, count: int) -> dict:
    key = "id" if _version_tuple(version) >= (1, 21, 0) else "item"
    return {key: item_id, "count": count}


def _pack_mcmeta(pack_format: int, description: str) -> str:
    return json.dumps({"pack": {"pack_format": pack_format, "description": description}}, indent=2) + "\n"


def _namespace(project_name: str, request: dict | None) -> str:
    if request and request.get("namespace"):
        return str(request["namespace"])
    return "".join(char.lower() for char in project_name if char.isalnum() or char == "_") or "mineforge"


def generate_paper_plugin(workspace: Path, project_name: str, package_name: str, request: dict | None = None) -> list[Path]:
    root = workspace / project_name
    java_dir = root / "src" / "main" / "java" / Path(package_name.replace(".", "/"))
    items_dir = java_dir / "items"
    listeners_dir = java_dir / "listeners"
    commands_dir = java_dir / "commands"
    resources = root / "src" / "main" / "resources"
    compatibility = select_java_compatibility("paper", (request or {}).get("version"))
    effective_version = compatibility.effective_version
    api_version = ".".join(effective_version.split(".")[:2])
    if (request or {}).get("feature") == "boss_arena":
        arena_dir = java_dir / "arena"
        boss_dir = java_dir / "boss"
        rewards_dir = java_dir / "rewards"
        files = []
        files.append(_write(root / ".gitignore", ".gradle/\nbuild/\n.idea/\nout/\n"))
        files.append(_write(root / "settings.gradle.kts", f'rootProject.name = "{project_name}"\n'))
        files.append(_write(root / "gradle.properties", f"org.gradle.jvmargs=-Xmx2G\norg.gradle.java.installations.auto-detect=true\npaperVersion={effective_version}\nprojectJavaVersion={compatibility.required_major}\n"))
        files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated by MineForgeAI Omniverse for Paper {effective_version}.\n\nFeatures:\n- `/stormboss start` spawns a storm boss at the player location.\n- `/stormboss stop` clears the active arena.\n- `/stormboss give` gives the lightning sword.\n- Boss bar, particles, lightning effects, config, permissions, and rewards.\n\nRequested version: {compatibility.requested_version}\nSelected version: {effective_version}\nJava requirement: {compatibility.required_major}+\nDetected Java: {installed_java_summary()}\nCompatibility: {compatibility.message}\n"))
        files.append(_write(root / "build.gradle.kts", f"""plugins {{ java }}

repositories {{
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}}

dependencies {{
    compileOnly("io.papermc.paper:paper-api:${{property("paperVersion")}}-R0.1-SNAPSHOT")
}}

java {{
    toolchain.languageVersion.set(JavaLanguageVersion.of(property("projectJavaVersion").toString().toInt()))
}}

tasks.withType<JavaCompile>().configureEach {{
    options.release.set(property("projectJavaVersion").toString().toInt())
}}
"""))
        files.append(_write(
            java_dir / f"{project_name}Plugin.java",
            f"""package {package_name};

import {package_name}.arena.BossArenaManager;
import {package_name}.boss.LightningSwordFactory;
import {package_name}.commands.StormBossCommand;
import {package_name}.listeners.BossArenaListener;
import {package_name}.rewards.RewardService;
import org.bukkit.Bukkit;
import org.bukkit.NamespacedKey;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.java.JavaPlugin;

public final class {project_name}Plugin extends JavaPlugin {{
    private BossArenaManager arenaManager;
    private LightningSwordFactory swordFactory;
    private RewardService rewardService;

    @Override
    public void onEnable() {{
        saveDefaultConfig();
        NamespacedKey swordKey = new NamespacedKey(this, "lightning_sword");
        swordFactory = new LightningSwordFactory(this, swordKey);
        rewardService = new RewardService(this, swordFactory);
        arenaManager = new BossArenaManager(this, rewardService);
        Bukkit.getPluginManager().registerEvents(new BossArenaListener(arenaManager, swordFactory), this);
        PluginCommand command = getCommand("stormboss");
        if (command != null) {{
            command.setExecutor(new StormBossCommand(this, arenaManager, swordFactory));
        }}
    }}

    @Override
    public void onDisable() {{
        if (arenaManager != null) {{
            arenaManager.stopArena();
        }}
    }}
}}
"""
        ))
        files.append(_write(
            arena_dir / "BossArenaManager.java",
            f"""package {package_name}.arena;

import {package_name}.rewards.RewardService;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Location;
import org.bukkit.Particle;
import org.bukkit.Sound;
import org.bukkit.World;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.LivingEntity;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitRunnable;

public final class BossArenaManager {{
    private final JavaPlugin plugin;
    private final RewardService rewards;
    private final Set<UUID> minions = new HashSet<>();
    private LivingEntity boss;
    private BossBar bossBar;
    private BukkitRunnable ticker;

    public BossArenaManager(JavaPlugin plugin, RewardService rewards) {{
        this.plugin = plugin;
        this.rewards = rewards;
    }}

    public boolean isRunning() {{
        return boss != null && !boss.isDead();
    }}

    public void startArena(Player owner) {{
        if (isRunning()) {{
            owner.sendMessage(ChatColor.RED + "A storm boss arena is already running.");
            return;
        }}
        Location center = owner.getLocation();
        World world = center.getWorld();
        boss = (LivingEntity) world.spawnEntity(center, EntityType.WITHER_SKELETON);
        boss.setCustomName(ChatColor.DARK_PURPLE + plugin.getConfig().getString("boss.name", "Storm Warden"));
        boss.setCustomNameVisible(true);
        boss.setRemoveWhenFarAway(false);
        bossBar = Bukkit.createBossBar(plugin.getConfig().getString("boss.name", "Storm Warden"), BarColor.PURPLE, BarStyle.SEGMENTED_10);
        for (Player player : world.getPlayers()) {{
            if (player.getLocation().distanceSquared(center) <= 2500) {{
                bossBar.addPlayer(player);
            }}
        }}
        spawnMinions(center);
        world.strikeLightningEffect(center);
        world.playSound(center, Sound.ENTITY_WITHER_SPAWN, 1.0f, 0.8f);
        startTicker(center);
        owner.sendMessage(ChatColor.AQUA + "Storm boss arena started.");
    }}

    public void stopArena() {{
        if (ticker != null) {{
            ticker.cancel();
            ticker = null;
        }}
        if (bossBar != null) {{
            bossBar.removeAll();
            bossBar = null;
        }}
        if (boss != null && !boss.isDead()) {{
            boss.remove();
        }}
        for (UUID id : minions) {{
            Entity entity = Bukkit.getEntity(id);
            if (entity != null) {{
                entity.remove();
            }}
        }}
        minions.clear();
        boss = null;
    }}

    public boolean isBoss(Entity entity) {{
        return boss != null && entity.getUniqueId().equals(boss.getUniqueId());
    }}

    public void handleBossDeath(Player killer) {{
        if (bossBar != null) {{
            bossBar.removeAll();
        }}
        if (killer != null) {{
            rewards.giveBossRewards(killer);
        }}
        stopArena();
    }}

    public void pulseLightning(Player player) {{
        if (!isRunning()) {{
            return;
        }}
        Location target = boss.getLocation();
        target.getWorld().strikeLightningEffect(target);
        target.getWorld().spawnParticle(Particle.ELECTRIC_SPARK, target.add(0, 1, 0), 40, 0.8, 0.8, 0.8, 0.05);
        target.getWorld().playSound(target, Sound.ENTITY_LIGHTNING_BOLT_THUNDER, 0.8f, 1.5f);
        player.sendMessage(ChatColor.YELLOW + "Your lightning sword calls the storm.");
    }}

    private void spawnMinions(Location center) {{
        int count = plugin.getConfig().getInt("arena.minions", 4);
        for (int i = 0; i < count; i++) {{
            Location at = center.clone().add((i % 2 == 0 ? 3 : -3), 0, i - 1);
            LivingEntity minion = (LivingEntity) center.getWorld().spawnEntity(at, EntityType.STRAY);
            minion.setCustomName(ChatColor.GRAY + "Storm Minion");
            minions.add(minion.getUniqueId());
        }}
    }}

    private void startTicker(Location center) {{
        ticker = new BukkitRunnable() {{
            @Override
            public void run() {{
                if (!isRunning()) {{
                    stopArena();
                    cancel();
                    return;
                }}
                double progress = Math.max(0.0, Math.min(1.0, boss.getHealth() / boss.getMaxHealth()));
                bossBar.setProgress(progress);
                center.getWorld().spawnParticle(Particle.CLOUD, boss.getLocation().add(0, 1, 0), 20, 0.7, 0.4, 0.7, 0.02);
            }}
        }};
        ticker.runTaskTimer(plugin, 0L, 20L);
    }}
}}
"""
        ))
        files.append(_write(
            boss_dir / "LightningSwordFactory.java",
            f"""package {package_name}.boss;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;

public final class LightningSwordFactory {{
    private final JavaPlugin plugin;
    private final NamespacedKey swordKey;

    public LightningSwordFactory(JavaPlugin plugin, NamespacedKey swordKey) {{
        this.plugin = plugin;
        this.swordKey = swordKey;
    }}

    public ItemStack createSword() {{
        ItemStack sword = new ItemStack(Material.DIAMOND_SWORD);
        ItemMeta meta = sword.getItemMeta();
        if (meta != null) {{
            meta.setDisplayName(ChatColor.AQUA + plugin.getConfig().getString("sword.name", "Stormcaller Blade"));
            meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_ENCHANTS);
            meta.getPersistentDataContainer().set(swordKey, PersistentDataType.BYTE, Byte.valueOf((byte) 1));
            sword.setItemMeta(meta);
        }}
        sword.addUnsafeEnchantment(Enchantment.SHARPNESS, plugin.getConfig().getInt("sword.sharpness", 5));
        return sword;
    }}

    public boolean isLightningSword(ItemStack stack) {{
        if (stack == null || !stack.hasItemMeta()) {{
            return false;
        }}
        ItemMeta meta = stack.getItemMeta();
        return meta != null && meta.getPersistentDataContainer().has(swordKey, PersistentDataType.BYTE);
    }}
}}
"""
        ))
        files.append(_write(
            java_dir / "listeners" / "BossArenaListener.java",
            f"""package {package_name}.listeners;

import {package_name}.arena.BossArenaManager;
import {package_name}.boss.LightningSwordFactory;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.entity.EntityDeathEvent;
import org.bukkit.event.player.PlayerInteractEvent;

public final class BossArenaListener implements Listener {{
    private final BossArenaManager arenaManager;
    private final LightningSwordFactory swordFactory;

    public BossArenaListener(BossArenaManager arenaManager, LightningSwordFactory swordFactory) {{
        this.arenaManager = arenaManager;
        this.swordFactory = swordFactory;
    }}

    @EventHandler
    public void onBossDeath(EntityDeathEvent event) {{
        if (!arenaManager.isBoss(event.getEntity())) {{
            return;
        }}
        Player killer = event.getEntity().getKiller();
        arenaManager.handleBossDeath(killer);
    }}

    @EventHandler
    public void onSwordUse(PlayerInteractEvent event) {{
        if (!swordFactory.isLightningSword(event.getItem())) {{
            return;
        }}
        arenaManager.pulseLightning(event.getPlayer());
    }}
}}
"""
        ))
        files.append(_write(
            java_dir / "commands" / "StormBossCommand.java",
            f"""package {package_name}.commands;

import {package_name}.arena.BossArenaManager;
import {package_name}.boss.LightningSwordFactory;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

public final class StormBossCommand implements CommandExecutor {{
    private final JavaPlugin plugin;
    private final BossArenaManager arenaManager;
    private final LightningSwordFactory swordFactory;

    public StormBossCommand(JavaPlugin plugin, BossArenaManager arenaManager, LightningSwordFactory swordFactory) {{
        this.plugin = plugin;
        this.arenaManager = arenaManager;
        this.swordFactory = swordFactory;
    }}

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {{
        if (args.length == 0) {{
            sender.sendMessage(ChatColor.YELLOW + "Usage: /stormboss <start|stop|give|reload>");
            return true;
        }}
        if (args[0].equalsIgnoreCase("reload")) {{
            plugin.reloadConfig();
            sender.sendMessage(ChatColor.GREEN + "Storm boss config reloaded.");
            return true;
        }}
        if (!(sender instanceof Player)) {{
            sender.sendMessage("Only players can use arena commands.");
            return true;
        }}
        Player player = (Player) sender;
        if (args[0].equalsIgnoreCase("start")) {{
            arenaManager.startArena(player);
            return true;
        }}
        if (args[0].equalsIgnoreCase("stop")) {{
            arenaManager.stopArena();
            player.sendMessage(ChatColor.GREEN + "Storm boss arena stopped.");
            return true;
        }}
        if (args[0].equalsIgnoreCase("give")) {{
            player.getInventory().addItem(swordFactory.createSword());
            player.sendMessage(ChatColor.AQUA + "You received the Stormcaller Blade.");
            return true;
        }}
        sender.sendMessage(ChatColor.YELLOW + "Usage: /stormboss <start|stop|give|reload>");
        return true;
    }}
}}
"""
        ))
        files.append(_write(
            rewards_dir / "RewardService.java",
            f"""package {package_name}.rewards;

import {package_name}.boss.LightningSwordFactory;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;

public final class RewardService {{
    private final JavaPlugin plugin;
    private final LightningSwordFactory swordFactory;

    public RewardService(JavaPlugin plugin, LightningSwordFactory swordFactory) {{
        this.plugin = plugin;
        this.swordFactory = swordFactory;
    }}

    public void giveBossRewards(Player player) {{
        int diamonds = plugin.getConfig().getInt("rewards.diamonds", 8);
        int experience = plugin.getConfig().getInt("rewards.experience", 250);
        player.getInventory().addItem(new ItemStack(Material.DIAMOND, diamonds));
        player.getInventory().addItem(swordFactory.createSword());
        player.giveExp(experience);
        player.sendMessage(ChatColor.GOLD + "Storm boss defeated. Rewards added.");
    }}
}}
"""
        ))
        files.append(_write(
            resources / "plugin.yml",
            f"""name: {project_name}
main: {package_name}.{project_name}Plugin
version: 1.0.0
api-version: '{api_version}'
commands:
  stormboss:
    description: Controls the storm boss arena
    usage: /stormboss <start|stop|give|reload>
    permission: {project_name.lower()}.stormboss
permissions:
  {project_name.lower()}.stormboss:
    default: op
"""
        ))
        files.append(_write(resources / "config.yml", """boss:
  name: Storm Warden
arena:
  minions: 4
sword:
  name: Stormcaller Blade
  sharpness: 5
rewards:
  diamonds: 8
  experience: 250
"""))
        return files
    files = []
    files.append(_write(root / ".gitignore", ".gradle/\nbuild/\n.idea/\nout/\n"))
    files.append(_write(root / "settings.gradle.kts", f'rootProject.name = "{project_name}"\n'))
    files.append(_write(root / "gradle.properties", f"org.gradle.jvmargs=-Xmx2G\norg.gradle.java.installations.auto-detect=true\npaperVersion={effective_version}\nprojectJavaVersion={compatibility.required_major}\n"))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated by MineForgeAI Omniverse for Paper {effective_version}.\n\nCommand: `/givesword`\nPermission: `{project_name.lower()}.givesword`\n\nRequested version: {compatibility.requested_version}\nSelected version: {effective_version}\nJava requirement: {compatibility.required_major}+\nDetected Java: {installed_java_summary()}\nCompatibility: {compatibility.message}\n"))
    files.append(_write(root / "build.gradle.kts", f"""plugins {{ java }}

repositories {{
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}}

dependencies {{
    compileOnly("io.papermc.paper:paper-api:${{property(\"paperVersion\")}}-R0.1-SNAPSHOT")
}}

java {{
    toolchain.languageVersion.set(JavaLanguageVersion.of(property("projectJavaVersion").toString().toInt()))
}}

tasks.withType<JavaCompile>().configureEach {{
    options.release.set(property("projectJavaVersion").toString().toInt())
}}
"""))
    files.append(_write(
        java_dir / f"{project_name}Plugin.java",
        f"package {package_name};\n\nimport {package_name}.commands.SwordCommand;\nimport {package_name}.items.SwordFactory;\nimport {package_name}.listeners.SwordListener;\nimport org.bukkit.Bukkit;\nimport org.bukkit.NamespacedKey;\nimport org.bukkit.command.PluginCommand;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class {project_name}Plugin extends JavaPlugin {{\n    private SwordFactory swordFactory;\n    private NamespacedKey swordKey;\n\n    @Override\n    public void onEnable() {{\n        saveDefaultConfig();\n        swordKey = new NamespacedKey(this, \"custom_sword\");\n        swordFactory = new SwordFactory(this, swordKey);\n        Bukkit.getPluginManager().registerEvents(new SwordListener(this, swordFactory), this);\n        PluginCommand command = getCommand(\"givesword\");\n        if (command != null) {{\n            command.setExecutor(new SwordCommand(swordFactory));\n        }}\n    }}\n}}\n"
    ))
    files.append(_write(
        items_dir / "SwordFactory.java",
        f"package {package_name}.items;\n\nimport org.bukkit.ChatColor;\nimport org.bukkit.Material;\nimport org.bukkit.NamespacedKey;\nimport org.bukkit.enchantments.Enchantment;\nimport org.bukkit.inventory.ItemFlag;\nimport org.bukkit.inventory.ItemStack;\nimport org.bukkit.inventory.ShapedRecipe;\nimport org.bukkit.inventory.meta.ItemMeta;\nimport org.bukkit.persistence.PersistentDataType;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class SwordFactory {{\n    private final JavaPlugin plugin;\n    private final NamespacedKey swordKey;\n\n    public SwordFactory(JavaPlugin plugin, NamespacedKey swordKey) {{\n        this.plugin = plugin;\n        this.swordKey = swordKey;\n        registerRecipe();\n    }}\n\n    public ItemStack createSword() {{\n        ItemStack sword = new ItemStack(Material.DIAMOND_SWORD);\n        ItemMeta meta = sword.getItemMeta();\n        if (meta != null) {{\n            meta.setDisplayName(ChatColor.AQUA + \"Omniverse Blade\");\n            meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES, ItemFlag.HIDE_ENCHANTS);\n            meta.getPersistentDataContainer().set(swordKey, PersistentDataType.BYTE, Byte.valueOf((byte) 1));\n            sword.setItemMeta(meta);\n        }}\n        sword.addUnsafeEnchantment(Enchantment.SHARPNESS, 5);\n        return sword;\n    }}\n\n    public boolean isCustomSword(ItemStack stack) {{\n        if (stack == null || !stack.hasItemMeta()) {{\n            return false;\n        }}\n        ItemMeta meta = stack.getItemMeta();\n        return meta != null && meta.getPersistentDataContainer().has(swordKey, PersistentDataType.BYTE);\n    }}\n\n    private void registerRecipe() {{\n        ShapedRecipe recipe = new ShapedRecipe(new NamespacedKey(plugin, \"omniverse_blade\"), createSword());\n        recipe.shape(\" ND\", \" SN\", \"S  \" );\n        recipe.setIngredient('N', Material.NETHER_STAR);\n        recipe.setIngredient('D', Material.DIAMOND);\n        recipe.setIngredient('S', Material.STICK);\n        plugin.getServer().addRecipe(recipe);\n    }}\n}}\n"
    ))
    files.append(_write(
        listeners_dir / "SwordListener.java",
        f"package {package_name}.listeners;\n\nimport {package_name}.items.SwordFactory;\nimport org.bukkit.Particle;\nimport org.bukkit.Sound;\nimport org.bukkit.entity.Entity;\nimport org.bukkit.entity.LivingEntity;\nimport org.bukkit.entity.Player;\nimport org.bukkit.event.EventHandler;\nimport org.bukkit.event.Listener;\nimport org.bukkit.event.entity.EntityDamageByEntityEvent;\nimport org.bukkit.event.player.PlayerInteractEvent;\nimport org.bukkit.inventory.ItemStack;\nimport org.bukkit.plugin.java.JavaPlugin;\n\npublic final class SwordListener implements Listener {{\n    private final JavaPlugin plugin;\n    private final SwordFactory swordFactory;\n\n    public SwordListener(JavaPlugin plugin, SwordFactory swordFactory) {{\n        this.plugin = plugin;\n        this.swordFactory = swordFactory;\n    }}\n\n    @EventHandler\n    public void onHit(EntityDamageByEntityEvent event) {{\n        Entity damager = event.getDamager();\n        Entity target = event.getEntity();\n        if (!(damager instanceof Player) || !(target instanceof LivingEntity)) {{\n            return;\n        }}\n        Player player = (Player) damager;\n        LivingEntity entity = (LivingEntity) target;\n        ItemStack item = player.getInventory().getItemInMainHand();\n        if (!swordFactory.isCustomSword(item)) {{\n            return;\n        }}\n        entity.getWorld().spawnParticle(Particle.END_ROD, entity.getLocation().add(0, 1, 0), 20, 0.3, 0.4, 0.3, 0.03);\n        entity.getWorld().playSound(entity.getLocation(), Sound.ENTITY_PLAYER_ATTACK_SWEEP, 1.0f, 1.2f);\n        player.setCooldown(item.getType(), plugin.getConfig().getInt(\"cooldown-seconds\", 5) * 20);\n    }}\n\n    @EventHandler\n    public void onRightClick(PlayerInteractEvent event) {{\n        ItemStack item = event.getItem();\n        if (!swordFactory.isCustomSword(item)) {{\n            return;\n        }}\n        Player player = event.getPlayer();\n        player.getWorld().spawnParticle(Particle.SOUL_FIRE_FLAME, player.getLocation().add(0, 1, 0), 30, 0.5, 0.5, 0.5, 0.02);\n        player.getWorld().playSound(player.getLocation(), Sound.ENTITY_LIGHTNING_BOLT_THUNDER, 0.5f, 1.7f);\n    }}\n}}\n"
    ))
    files.append(_write(
        commands_dir / "SwordCommand.java",
        f"package {package_name}.commands;\n\nimport {package_name}.items.SwordFactory;\nimport org.bukkit.command.Command;\nimport org.bukkit.command.CommandExecutor;\nimport org.bukkit.command.CommandSender;\nimport org.bukkit.entity.Player;\n\npublic final class SwordCommand implements CommandExecutor {{\n    private final SwordFactory swordFactory;\n\n    public SwordCommand(SwordFactory swordFactory) {{\n        this.swordFactory = swordFactory;\n    }}\n\n    @Override\n    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {{\n        if (!(sender instanceof Player)) {{\n            sender.sendMessage(\"Only players can use this command.\");\n            return true;\n        }}\n        Player player = (Player) sender;\n        player.getInventory().addItem(swordFactory.createSword());\n        player.sendMessage(\"You received the Omniverse Blade.\");\n        return true;\n    }}\n}}\n"
    ))
    files.append(_write(
        resources / "plugin.yml",
        f"name: {project_name}\nmain: {package_name}.{project_name}Plugin\nversion: 1.0.0\napi-version: '{api_version}'\ncommands:\n  givesword:\n    description: Gives the Omniverse Blade\n    usage: /givesword\n    permission: {project_name.lower()}.givesword\npermissions:\n  {project_name.lower()}.givesword:\n    default: op\n"
    ))
    files.append(_write(resources / "config.yml", "cooldown-seconds: 5\ntrail-enabled: true\nright-click-ability: true\n"))
    return files


def generate_fabric_mod(workspace: Path, project_name: str, package_name: str, request: dict | None = None) -> list[Path]:
    root = workspace / project_name
    java_dir = root / "src" / "main" / "java" / Path(package_name.replace(".", "/"))
    resources = root / "src" / "main" / "resources"
    compatibility = select_java_compatibility("fabric", (request or {}).get("version"))
    effective_version = compatibility.effective_version
    version_data = fabric_version_data(effective_version)
    files = []
    files.append(_write(root / ".gitignore", ".gradle/\nbuild/\n.idea/\nout/\nrun/\n"))
    files.append(_write(root / "settings.gradle.kts", f'rootProject.name = "{project_name}"\n'))
    files.append(_write(root / "gradle.properties", f"org.gradle.jvmargs=-Xmx2G\norg.gradle.java.installations.auto-detect=true\nminecraft_version={effective_version}\nyarn_mappings={version_data['yarn_mappings']}\nloader_version={version_data['loader_version']}\nfabric_version={version_data['fabric_version']}\nprojectJavaVersion={compatibility.required_major}\n"))
    files.append(_write(root / "build.gradle.kts", f"""plugins {{
    id(\"fabric-loom\") version \"1.7-SNAPSHOT\"
    java
}}

repositories {{
    mavenCentral()
    maven(\"https://maven.fabricmc.net/\")
}}

dependencies {{
    minecraft(\"com.mojang:minecraft:${{property(\\\"minecraft_version\\\")}}\")
    mappings(\"net.fabricmc:yarn:${{property(\\\"yarn_mappings\\\")}}:v2\")
    modImplementation(\"net.fabricmc:fabric-loader:${{property(\\\"loader_version\\\")}}\")
    modImplementation(\"net.fabricmc.fabric-api:fabric-api:${{property(\\\"fabric_version\\\")}}\")
}}

java {{
    toolchain.languageVersion.set(JavaLanguageVersion.of(property("projectJavaVersion").toString().toInt()))
}}

tasks.withType<JavaCompile>().configureEach {{
    options.release.set(property("projectJavaVersion").toString().toInt())
}}
"""))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated by MineForgeAI Omniverse for Fabric {effective_version}.\n\nRequested version: {compatibility.requested_version}\nSelected version: {effective_version}\nJava requirement: {compatibility.required_major}+\nDetected Java: {installed_java_summary()}\nCompatibility: {compatibility.message}\n"))
    files.append(_write(
        java_dir / f"{project_name}Mod.java",
        f"package {package_name};\n\nimport net.fabricmc.api.ModInitializer;\n\npublic final class {project_name}Mod implements ModInitializer {{\n    public static final String MOD_ID = \"{project_name.lower()}\";\n\n    @Override\n    public void onInitialize() {{\n    }}\n}}\n"
    ))
    files.append(_write(
        resources / "fabric.mod.json",
        json.dumps(
            {
                "schemaVersion": 1,
                "id": project_name.lower(),
                "version": "1.0.0",
                "name": project_name,
                "description": f"Generated Fabric mod for Minecraft {effective_version}",
                "environment": "*",
                "entrypoints": {"main": [f"{package_name}.{project_name}Mod"]},
                "depends": {"fabricloader": f">={version_data['loader_version']}", "minecraft": effective_version},
            },
            indent=2,
        ) + "\n"
    ))
    return files


def generate_datapack(workspace: Path, project_name: str, request: dict | None = None) -> list[Path]:
    version = (request or {}).get("version", "1.21.1")
    namespace = _namespace(project_name, request)
    root = workspace / project_name
    data_root = root / "data" / namespace
    minecraft_root = root / "data" / "minecraft"
    folders = _datapack_folder_names(version)
    function_dir = folders["function"]
    advancement_dir = folders["advancement"]
    recipe_dir = folders["recipe"]
    pack_format = _pack_format(version)
    files = []
    files.append(_write(root / "pack.mcmeta", _pack_mcmeta(pack_format, f"{project_name} datapack for Minecraft {version}")))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated datapack for Minecraft {version}.\n\nInstall by copying this folder into a world's `datapacks` directory, then run `/reload`.\n\nFunctions:\n- `{namespace}:load`\n- `{namespace}:tick`\n- `{namespace}:start_trial`\n- `{namespace}:reward`\n"))
    files.append(_write(
        minecraft_root / "tags" / "function" / "load.json",
        json.dumps({"values": [f"{namespace}:load"]}, indent=2) + "\n",
    ))
    files.append(_write(
        minecraft_root / "tags" / "function" / "tick.json",
        json.dumps({"values": [f"{namespace}:tick"]}, indent=2) + "\n",
    ))
    if _version_tuple(version) < (1, 21, 0):
        (minecraft_root / "tags" / "functions").mkdir(parents=True, exist_ok=True)
        files.append(_write(minecraft_root / "tags" / "functions" / "load.json", json.dumps({"values": [f"{namespace}:load"]}, indent=2) + "\n"))
        files.append(_write(minecraft_root / "tags" / "functions" / "tick.json", json.dumps({"values": [f"{namespace}:tick"]}, indent=2) + "\n"))
    files.append(_write(data_root / function_dir / "load.mcfunction", f"scoreboard objectives add {namespace}_timer dummy\nscoreboard objectives add {namespace}_wins dummy\nsay [{project_name}] datapack loaded\n"))
    files.append(_write(data_root / function_dir / "tick.mcfunction", f"execute as @a[scores={{{namespace}_timer=1..}}] run scoreboard players remove @s {namespace}_timer 1\nexecute as @a[scores={{{namespace}_timer=0}}] run function {namespace}:reward\n"))
    files.append(_write(data_root / function_dir / "start_trial.mcfunction", f"scoreboard players set @s {namespace}_timer 200\nplaysound minecraft:block.beacon.activate master @s ~ ~ ~ 1 1\nparticle minecraft:end_rod ~ ~1 ~ 0.5 0.5 0.5 0.02 30 force @a[distance=..32]\ntellraw @s {{\"text\":\"Trial started. Survive the storm for 10 seconds.\",\"color\":\"aqua\"}}\n"))
    files.append(_write(data_root / function_dir / "reward.mcfunction", f"scoreboard players set @s {namespace}_timer -1\nscoreboard players add @s {namespace}_wins 1\ngive @s minecraft:diamond 3\nexperience add @s 50 points\ntellraw @s {{\"text\":\"Trial complete. Reward granted.\",\"color\":\"gold\"}}\n"))
    files.append(_write(
        data_root / advancement_dir / "start_trial.json",
        json.dumps(
            {
                "criteria": {"use_beacon": {"trigger": "minecraft:inventory_changed", "conditions": {"items": [{"items": ["minecraft:beacon"]}]}}},
                "rewards": {"function": f"{namespace}:start_trial"},
            },
            indent=2,
        ) + "\n",
    ))
    files.append(_write(
        data_root / recipe_dir / "storm_trial_key.json",
        json.dumps(
            {
                "type": "minecraft:crafting_shaped",
                "pattern": [" E ", "DND", " E "],
                "key": {
                    "E": {"item": "minecraft:ender_pearl"},
                    "D": {"item": "minecraft:diamond"},
                    "N": {"item": "minecraft:nether_star"},
                },
                "result": _recipe_result(version, "minecraft:beacon", 1),
            },
            indent=2,
        ) + "\n",
    ))
    return files


def generate_resource_pack(workspace: Path, project_name: str, request: dict | None = None) -> list[Path]:
    version = (request or {}).get("version", "1.21.1")
    namespace = _namespace(project_name, request)
    root = workspace / project_name
    assets = root / "assets" / namespace
    pack_format = _pack_format(version)
    files = []
    files.append(_write(root / "pack.mcmeta", _pack_mcmeta(pack_format, f"{project_name} resource pack for Minecraft {version}")))
    files.append(_write(root / "README.md", f"# {project_name}\n\nGenerated resource pack for Minecraft {version}.\n\nInstall by copying this folder into `.minecraft/resourcepacks`, then enable it in the client resource pack menu.\n"))
    files.append(_write(
        assets / "lang" / "en_us.json",
        json.dumps(
            {
                f"item.{namespace}.storm_blade": "Storm Blade",
                f"item.{namespace}.storm_crystal": "Storm Crystal",
            },
            indent=2,
        ) + "\n",
    ))
    files.append(_write(
        assets / "models" / "item" / "storm_blade.json",
        json.dumps(
            {
                "parent": "minecraft:item/handheld",
                "textures": {"layer0": f"{namespace}:item/storm_blade"},
            },
            indent=2,
        ) + "\n",
    ))
    files.append(_write(
        assets / "models" / "item" / "storm_crystal.json",
        json.dumps(
            {
                "parent": "minecraft:item/generated",
                "textures": {"layer0": f"{namespace}:item/storm_crystal"},
            },
            indent=2,
        ) + "\n",
    ))
    files.append(_write(
        assets / "atlases" / "blocks.json",
        json.dumps({"sources": [{"type": "directory", "source": "item", "prefix": "item/"}]}, indent=2) + "\n",
    ))
    files.append(_write_bytes(assets / "textures" / "item" / "storm_blade.png", _png_rgba(16, 16, (45, 180, 255, 255))))
    files.append(_write_bytes(assets / "textures" / "item" / "storm_crystal.png", _png_rgba(16, 16, (155, 90, 255, 255))))
    return files
