name: PaperPlugin
main: com.mineforgeai.customsword.PaperPluginPlugin
version: 1.0.0
api-version: '1.21'
commands:
  givesword:
    description: Gives the Omniverse Blade
    usage: /givesword
    permission: paperplugin.givesword
permissions:
  paperplugin.givesword:
    default: op
