from __future__ import annotations

DEFAULT_CONFIG = {
    "project": {"name": "MineForgeAI Omniverse", "workspace_mode": "current_directory_only"},
    "install": {
        "npm_wrapper": True,
        "python_backend": True,
        "auto_create_venv": True,
        "auto_install_requirements": True,
        "user_data_dir": "auto",
        "cache_dir": "auto",
    },
    "device": {
        "auto_detect": True,
        "prefer_cuda": True,
        "prefer_rocm": True,
        "prefer_mps": True,
        "allow_cpu": True,
        "mixed_precision": "auto",
    },
    "training": {
        "from_scratch": True,
        "train_hours": 6,
        "resume": True,
        "checkpoint_dir": "checkpoints",
        "final_model_dir": "models/latest",
        "save_every_minutes": 10,
        "eval_every_minutes": 10,
    },
    "chat": {
        "auto_start_model": True,
        "default_mode": "chatbot",
        "auto_compact": True,
        "compact_at_context_percent": 75,
        "keep_recent_messages": 20,
        "virtual_context_window_tokens": 131072,
        "high_end_virtual_context_window_tokens": 262144,
    },
    "permissions": {
        "default_mode": "ask_before_actions",
        "allowed_modes": ["see_edits", "ask_before_actions", "full_access"],
        "show_diffs_before_edit": True,
        "block_dangerous_commands": True,
        "block_workspace_escape": True,
    },
    "web": {
        "enabled": False,
        "controlled_by_command_only": True,
        "command_on": "/web on",
        "command_off": "/web off",
        "prefer_official_docs": True,
        "respect_robots_txt": True,
        "block_piracy": True,
    },
    "agent": {
        "natural_language_only": True,
        "slash_commands_allowed": ["/permisions", "/web on", "/web off"],
        "subagents_enabled": True,
        "workspace_root": "cwd",
        "allow_outside_workspace": False,
        "safe_shell_mode": True,
        "max_files_read_per_turn": 30,
        "max_file_chars": 30000,
    },
    "minecraft": {
        "version_manifest": True,
        "include_snapshots": True,
        "include_old_alpha_beta": True,
        "all_subversions": True,
        "adapters": "all",
    },
    "minecraft_intel": {
        "enabled": True,
        "require_user_confirmation_for_jar_analysis": True,
        "allow_download_version_metadata": True,
        "allow_download_jars": False,
        "local_only_sources": True,
        "decompile_enabled": "ask",
        "cache_dir": ".mineforgeai/minecraft_sources",
        "index_dir": ".minecraft_index",
        "never_export_raw_source": True,
    },
}
